package com.phonewebmcp.gu;

/**
 * 内置 Web 控制台页面。手机浏览器访问 http://127.0.0.1:8765 即可可视化控制。
 */
public class ConsoleHtml {
    public static String build(String token) {
        String html = "<!DOCTYPE html><html lang=\"zh\"><head><meta charset=\"utf-8\">"
                + "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
                + "<title>WebView 调试器控制台</title><style>"
                + "body{font-family:system-ui,sans-serif;margin:0;background:#0f172a;color:#e2e8f0;padding-bottom:40px}"
                + "header{background:#1e293b;padding:14px 16px;display:flex;align-items:center;gap:10px;flex-wrap:wrap}"
                + "header h1{font-size:17px;margin:0;flex:1}"
                + ".card{background:#1e293b;margin:12px;padding:14px;border-radius:12px}"
                + ".card h2{margin:0 0 10px;font-size:14px;color:#93c5fd}"
                + "input,select,button{font-size:14px;padding:8px 10px;border-radius:8px;border:1px solid #334155;background:#0f172a;color:#e2e8f0;outline:none}"
                + "input{flex:1;min-width:120px}"
                + "button{background:#2563eb;border:none;cursor:pointer}"
                + "button:hover{background:#1d4ed8}"
                + ".row{display:flex;gap:8px;margin-bottom:8px;flex-wrap:wrap}"
                + "label{font-size:13px;color:#94a3b8}"
                + "pre{background:#0b1120;padding:10px;border-radius:8px;overflow:auto;font-size:12px;max-height:240px;white-space:pre-wrap;word-break:break-all}"
                + "#status{font-size:12px;color:#94a3b8}"
                + ".pill{background:#334155;padding:2px 8px;border-radius:10px;font-size:12px}"
                + ".ok{color:#4ade80}.err{color:#f87171}"
                + "</style></head><body>"
                + "<header><h1>WebView 调试器 · 控制台</h1><span class=\"pill\">token 已内置</span></header>"
                + "<div class=\"card\"><h2>状态</h2><div id=\"status\">加载中...</div></div>"
                + "<div class=\"card\"><h2>导航</h2>"
                + "<div class=\"row\"><input id=\"url\" placeholder=\"输入网址，如 https://example.com\"><button onclick=\"nav()\">前往</button></div>"
                + "<div class=\"row\"><select id=\"engine\">"
                + "<option value=\"baidu\">百度</option><option value=\"bing\">必应</option><option value=\"google\">谷歌</option>"
                + "<option value=\"sogou\">搜狗</option><option value=\"so\">360</option><option value=\"github\">GitHub</option><option value=\"zhihu\">知乎</option>"
                + "</select><input id=\"q\" placeholder=\"搜索关键词\"><button onclick=\"search()\">搜索</button></div>"
                + "<div class=\"row\"><button onclick=\"api('back')\">← 后退</button><button onclick=\"api('forward')\">前进 →</button>"
                + "<button onclick=\"api('reload')\">⟳ 刷新</button><button onclick=\"api('stop')\">⏹ 停止</button><button onclick=\"api('home')\">⌂ 主页</button></div></div>"
                + "<div class=\"card\"><h2>JS 执行</h2><div class=\"row\"><input id=\"js\" placeholder=\"输入 JavaScript，如 document.title\"><button onclick=\"evaluate()\">执行</button></div><pre id=\"jsResult\"></pre></div>"
                + "<div class=\"card\"><h2>页面信息</h2><button onclick=\"dom()\">获取 DOM 摘要</button> <button onclick=\"links()\">获取链接列表</button> <button onclick=\"shot()\">截图</button><pre id=\"domResult\"></pre></div>"
                + "<div class=\"card\"><h2>缓存与数据</h2>"
                + "<div class=\"row\"><button onclick=\"api('cache/clear')\">清缓存</button><button onclick=\"api('cookies/clear')\">清 Cookie</button>"
                + "<button onclick=\"api('form/clear')\">清表单</button><button onclick=\"api('clear-all')\">清全部</button></div></div>"
                + "<div class=\"card\"><h2>Cookie</h2><div class=\"row\"><input id=\"cookUrl\" placeholder=\"域名，如 https://example.com\"><button onclick=\"cookies()\">查看</button></div><pre id=\"cookieResult\"></pre></div>"
                + "<div class=\"card\"><h2>设置</h2>"
                + "<div class=\"row\"><label>UA</label><select id=\"ua\" onchange=\"setSetting('userAgent',this.value)\">"
                + "<option value=\"mobile\">移动端默认</option><option value=\"desktop\">桌面端</option><option value=\"wechat\">微信</option></select></div>"
                + "<div class=\"row\"><label>缓存模式</label><select id=\"cm\" onchange=\"setSetting('cacheMode',this.value)\">"
                + "<option value=\"LOAD_DEFAULT\">默认</option><option value=\"LOAD_CACHE_ELSE_NETWORK\">优先缓存</option>"
                + "<option value=\"LOAD_NO_CACHE\">禁用缓存</option><option value=\"LOAD_CACHE_ONLY\">仅缓存</option></select></div>"
                + "<div class=\"row\"><label>JavaScript</label><select id=\"jsOn\" onchange=\"setSetting('javaScript',this.value)\"><option value=\"true\">开</option><option value=\"false\">关</option></select>"
                + "<label>DOM Storage</label><select id=\"ds\" onchange=\"setSetting('domStorage',this.value)\"><option value=\"true\">开</option><option value=\"false\">关</option></select>"
                + "<label>Safe Browsing</label><select id=\"sb\" onchange=\"setSetting('safeBrowsing',this.value)\"><option value=\"true\">开</option><option value=\"false\">关</option></select></div></div>"
                + "<script>"
                + "const T='%TOKEN%';"
                + "async function call(p,body){const opt={method:body?'POST':'GET',headers:{'X-Api-Token':T}};"
                + "if(body){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(body)}"
                + "const r=await fetch(p,opt);return r.json()}"
                + "async function refresh(){const s=await call('/api/status');"
                + "document.getElementById('status').innerHTML='<b>'+esc(s.result.title||'无标题')+'</b><br>'+esc(s.result.url||'')"
                + "+'<br>进度: '+s.result.progress+'% · 可后退:'+s.result.canGoBack+' · 可前进:'+s.result.canGoForward}"
                + "function nav(){call('/api/navigate',{url:document.getElementById('url').value}).then(refresh)}"
                + "function search(){const e=document.getElementById('engine').value,q=document.getElementById('q').value;"
                + "call('/api/search',{engine:e,query:q}).then(refresh)}"
                + "function api(p){call('/api/'+p).then(x=>{refresh();show(JSON.stringify(x))})}"
                + "function evaluate(){const js=document.getElementById('js').value;"
                + "call('/api/evaluate',{js}).then(x=>{document.getElementById('jsResult').textContent=x.ok?x.result:'错误: '+x.error})}"
                + "function dom(){call('/api/dom').then(x=>document.getElementById('domResult').textContent=JSON.stringify(x,null,2))}"
                + "function links(){call('/api/links').then(x=>document.getElementById('domResult').textContent=JSON.stringify(x,null,2))}"
                + "function shot(){call('/api/screenshot').then(x=>{if(x.ok){const img=document.createElement('img');img.src=x.result;"
                + "document.getElementById('domResult').innerHTML='';document.getElementById('domResult').appendChild(img)}"
                + "else document.getElementById('domResult').textContent='错误: '+x.error})}"
                + "function cookies(){const u=document.getElementById('cookUrl').value;"
                + "call('/api/cookies?url='+encodeURIComponent(u)).then(x=>document.getElementById('cookieResult').textContent=JSON.stringify(x,null,2))}"
                + "function setSetting(k,v){call('/api/settings',{key:k,value:v}).then(x=>show(JSON.stringify(x)))}"
                + "const UAS={mobile:'',desktop:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',"
                + "wechat:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.0.0 Mobile Safari/537.36 MicroMessenger/8.0.49'};"
                + "document.querySelector('#ua').onchange=e=>{const v=UAS[e.target.value];call('/api/settings',{key:'userAgent',value:v}).then(x=>show(JSON.stringify(x)))}"
                + "function show(t){const d=document.getElementById('jsResult');d.textContent=t}"
                + "function esc(s){return (s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}"
                + "refresh();setInterval(refresh,3000);"
                + "</script></body></html>";
        return html.replace("%TOKEN%", token);
    }
}
